[tools.mise]
scopes = ["global"]
command = ["mise", "completion", "zsh"]

[tools.gh]
scopes = ["global"]
command = ["gh", "completion", "-s", "zsh"]

[tools.docker]
scopes = ["global"]
command = ["docker", "completion", "zsh"]

[tools.starship]
scopes = ["global"]
command = ["starship", "completions", "zsh"]

[tools.rclone]
scopes = ["global"]
command = ["rclone", "completion", "zsh", "-"]

[tools.kubectl]
scopes = ["project"]
command = ["kubectl", "completion", "zsh"]

[tools.helm]
scopes = ["project"]
command = ["helm", "completion", "zsh"]

[tools.uv]
scopes = ["global", "project"]
command = ["uv", "generate-shell-completion", "zsh"]

[tools.pnpm]
scopes = ["global", "project"]
command = ["pnpm", "completion", "zsh"]

[tools.aube]
scopes = ["global", "project"]
command = ["aube", "completion", "zsh"]

[tools.bun]
scopes = ["project"]
command = ["bun", "completion", "zsh"]

[tools.chezmoi]
scopes = ["global"]
command = ["chezmoi", "completion", "zsh"]

[tools.betterleaks]
scopes = ["global"]
command = ["betterleaks", "completion", "zsh"]

[tools.cargo]
scopes = ["global", "project"]
command = ["rustup", "completions", "zsh", "cargo"]

[tools.rustup]
scopes = ["global", "project"]
command = ["rustup", "completions", "zsh"]

[tools.bw]
scopes = ["global"]
command = ["bw", "completion", "--shell", "zsh"]

[tools.jj]
scopes = ["global", "project"]
env = { COMPLETE = "zsh" }
command = ["jj"]

[tools.zcs]
scopes = ["global"]
command = ["zcs", "completion", "zsh"]

[tools.rmux]
scopes = ["global"]
file = { git = "https://github.com/YewFence/zsh-completions-sync.git", path = "completions/_rmux", ref = "main" }
